Repository Jacob-Polane/graduate-demo-project, pull requests merged in 2025-02, with the labels that each got.

#16 unclosedTag
  App.html
Labels: bug

#17 Add missing 'type' attribute to the button 'send'
  App.html
Labels: Complete

#47 Added a label for the checkbox
  App.html
Labels: review ready
